import "server-only";
import Anthropic from "@anthropic-ai/sdk";
import { deidentify } from "@/lib/deidentify";

// Counseling-assist engine. Design locked in COUNSELING-ASSIST.md (deep-research
// verified): coach the LEADER, never diagnose the member; CCEF/"idols of the heart"
// (Powlison/Tripp) voice via Keller's Counterfeit Gods; hard escalation; and the
// idol-lens is offered as a possibility for the leader to hold gently, never a verdict
// about the member. De-identification (deidentify.ts) + this leader-facing framing are
// the two safeguards. Gated behind COUNSEL_ENABLED + pastoral-only until legal clears.

export const COUNSEL_ENABLED = process.env.COUNSEL_ENABLED === "true";

// Deterministic crisis pre-check — if any of these appear we ALWAYS surface the
// referral block, regardless of what the model returns. Belt to the model's braces.
const CRISIS_PATTERNS =
  /\b(suicid|kill (?:myself|himself|herself|themsel)|want(?:s|ed)? to die|end (?:it|my life|his life|her life)|self.?harm|cut(?:ting)? (?:myself|himself|herself)|overdos|abus|assault|rape|raped|hitting (?:me|her|him)|hurt(?:s|ing)? (?:me|her|him)|starv|not eating|throwing up (?:food|meals)|psychosis|hallucinat|hopeless|can'?t go on|no reason to live)\b/i;

// Deterministic referral text — never generated by the model. Full per-campus list
// lives in REFERRAL-LIST.md; this is the always-in-front-of-you crisis core.
export const CRISIS_REFERRAL =
  "If they're in danger right now: 988 (call or text) · Crisis Text Line (text HOME to 741741) · 911. " +
  "Campus lines — NYU Wellness Exchange 999-555-0000 (24/7), Columbia CPS 999-555-0001. " +
  "This is bigger than a hangout leader: loop in a pastor (Alex or Priya) today, and stay with them until they're connected.";

export type CounselGuidance = {
  reflectiveQuestions: string[];
  lens: string;
  scriptureRef: string;
  scriptureWhy: string;
  posture: string;
  escalate: boolean;
  escalationNote: string;
  crisis: boolean; // true if the deterministic pre-check fired
  referral: string | null; // populated iff crisis
  live: boolean; // false = model not called (flag off / no key) — never happens on success
};

const SYSTEM = `You are a shepherding coach for a LAY college small-group leader in a campus ministry (R20). You coach the LEADER on how to care for someone in their group. You are NOT a therapist and you do NOT counsel or diagnose the member — everything you say is addressed to the leader about their own posture and next step.

Voice: gospel-centered "biblical counseling" in the CCEF tradition (Powlison, Tripp) — people as both sinners and sufferers, address suffering before sin, soft not confrontational. Draw on Tim Keller's "idols of the heart" / Counterfeit Gods frame.

Hard rules:
- Coach the leader's heart and approach. Never produce a diagnosis, label, or verdict about the member.
- The "idol" lens is offered as ONE possibility for the leader to hold gently and prayerfully — never as a certainty about what is "really" going on. Frame it tentatively.
- Lead with warmth and presence over fixing. The leader is an elder-brother, not a junior pastor.
- Reinforce escalation, never replace it. If there's any hint of danger to self or others, abuse, or a mental-health crisis, set escalate=true and say plainly that this is beyond a lay leader and a pastor + professional must be looped in.
- No Christianese, no clichés, no false certainty. Be plain and human.
- You will NOT receive the member's name or contact details (they are stripped before you see this). Never ask for them.

Return concise, usable guidance.`;

const SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    reflectiveQuestions: {
      type: "array",
      items: { type: "string" },
      description: "2-4 questions for the LEADER to sit with (about their own posture and how to be present), not to interrogate the member with.",
    },
    lens: {
      type: "string",
      description: "One gentle, tentatively-framed observation using the idols/identity/grace lens — a possibility for the leader to hold, never a verdict about the member.",
    },
    scriptureRef: { type: "string", description: "One fitting Scripture reference." },
    scriptureWhy: { type: "string", description: "One sentence on why it fits — for the leader's own meditation." },
    posture: { type: "string", description: "One concrete, warm next step for the leader (be with, not fix)." },
    escalate: { type: "boolean", description: "True if this may exceed lay care (danger, abuse, crisis, or persistent/severe struggle)." },
    escalationNote: { type: "string", description: "If escalate, one sentence naming what to do (loop in a pastor; involve a professional). Empty string if not." },
  },
  required: ["reflectiveQuestions", "lens", "scriptureRef", "scriptureWhy", "posture", "escalate", "escalationNote"],
} as const;

/**
 * Coach the leader on a situation. `situation` is the leader's own free-text
 * description; `names` is the roster names to scrub. Member-identifying content is
 * de-identified before the model sees it. Throws if the tool is disabled/unconfigured.
 */
export async function counselLeader(situation: string, names: string[]): Promise<CounselGuidance> {
  if (!COUNSEL_ENABLED) throw new Error("Counseling assist is not enabled.");
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error("Counseling assist is not configured.");

  const crisis = CRISIS_PATTERNS.test(situation);
  const safe = deidentify(situation.trim(), names);

  const client = new Anthropic({ apiKey });
  const resp = await client.messages.create({
    model: "claude-opus-4-8",
    max_tokens: 2000,
    thinking: { type: "adaptive" },
    system: SYSTEM,
    output_config: { format: { type: "json_schema", schema: SCHEMA } },
    messages: [
      {
        role: "user",
        content: `A leader I coach wrote this about someone in their group (identifying details already removed):\n\n"${safe}"\n\nCoach the leader.`,
      },
    ],
  });

  const text = resp.content.find((b) => b.type === "text");
  if (!text || text.type !== "text") throw new Error("No guidance returned.");
  const g = JSON.parse(text.text) as Omit<CounselGuidance, "crisis" | "referral" | "live">;

  return {
    ...g,
    escalate: g.escalate || crisis,
    crisis,
    referral: crisis ? CRISIS_REFERRAL : null,
    live: true,
  };
}
